spring:
  # 运行环境
  profiles:
    active: local
  # 应用名称
  application:
    name: zy-base
# mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/zy/base/**/xml/*.xml # 扫描mapper文件夹下的所有.xml结尾的文件
# 获取pom文件的属性
pom:
  version: 1.0.1 # 项目版本号