spring:
  cloud:
    nacos:
      server-addr: xxx # nacos服务器地址
  config:
    import:
      - nacos:zy-common-prod.yaml                       # 通用配置文件
      - nacos:zy-base-prod.yaml?group=ZY_BUSINESS_GROUP # 当前项目配置文件