spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos服务器地址
  config:
    import:
      - nacos:zy-common-local.yaml                          # 通用配置文件
      - nacos:zy-produce-local.yaml?group=ZY_BUSINESS_GROUP # 当前项目配置文件